// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/file_service.proto
// Protobuf Java Version: 4.28.2

package br.edu.ifpb.pdist_back.grpc;

public final class FileServiceProto {
  private FileServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      FileServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UploadFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!src/main/proto/file_service.proto\"Z\n\007F" +
      "ileDTO\022\016\n\006userId\030\001 \001(\t\022\020\n\010filename\030\002 \001(\t" +
      "\022\023\n\013contentType\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\022\n\n\002i" +
      "d\030\005 \001(\t\"\034\n\016GetFileRequest\022\n\n\002id\030\001 \001(\t\" \n" +
      "\022UploadFileResponse\022\n\n\002id\030\001 \001(\t2d\n\013FileS" +
      "ervice\022+\n\nuploadFile\022\010.FileDTO\032\023.UploadF" +
      "ileResponse\022(\n\013getFileById\022\017.GetFileRequ" +
      "est\032\010.FileDTOB&\n\020org.example.grpcB\020FileS" +
      "erviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FileDTO_descriptor,
        new String[] { "UserId", "Filename", "ContentType", "Data", "Id", });
    internal_static_GetFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetFileRequest_descriptor,
        new String[] { "Id", });
    internal_static_UploadFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UploadFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UploadFileResponse_descriptor,
        new String[] { "Id", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
