// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/file_service.proto
// Protobuf Java Version: 4.28.2

package br.edu.ifpb.pdist_back.grpc;

public interface FileDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  String getFilename();
  /**
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string contentType = 3;</code>
   * @return The contentType.
   */
  String getContentType();
  /**
   * <code>string contentType = 3;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string id = 5;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 5;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
