// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/file_service.proto
// Protobuf Java Version: 4.28.2

package br.edu.ifpb.pdist_back.grpc;

public interface GetFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
